name: Run PHPStan

inputs:
  php:
    required: true
    type: string
    description: PHP version to use in major.minor format (e.g. 8.0)
  GITHUB_TOKEN:
    required: true
    type: string
    description: GitHub token for Composer cache

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false

    - name: Install PHP
      uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      id: composer-cache
      run: | #shell
        echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-${{ inputs.php }}-${{ hashFiles('composer.json') }}

    - name: PHPStan cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      with:
        path: tests/cache/phpstan
        key: phpstan-${{ inputs.php }}-${{ hashFiles('composer.json') }}-${{ hashFiles('phpstan.neon.dist') }}

    - name: Install dependencies
      run: | #shell
        composer install

    - name: Run static analysis
      run: | #shell
        composer run test:phpstan
