# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Publish

on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@johnbillion/plugin-infrastructure
    timeout-minutes: 10
    permissions:
      contents: read  # Required to clone the repository
      id-token: write # Required for creating an OIDC token so `npm publish` can:
                      # 1. Authenticate with npm for OIDC trusted publishing
                      # 2. Obtain a signing certificate from Sigstore for its provenance attestation
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install
        run: npm ci --no-audit --no-fund --ignore-scripts

      - name: Build
        run: npm run build

      - name: Publish via OIDC trusted publishing
        run: | #shell
          if [[ "$GITHUB_REF_NAME" == *"-"* ]]; then
            npm publish --access public --tag beta
          else
            npm publish --access public
          fi
