# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Publish

on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  npm:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@johnbillion/plugin-infrastructure
    timeout-minutes: 10
    permissions:
      contents: read  # Required to clone the repository
      id-token: write # Required for creating an OIDC token so `npm publish` can:
                      # 1. Authenticate with npm for OIDC trusted publishing
                      # 2. Obtain a signing certificate from Sigstore for its provenance attestation
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Publish via OIDC trusted publishing
        run: | #shell
          if [[ "$GITHUB_REF_NAME" == *"-"* ]]; then
            npm publish --access public --tag beta
          else
            npm publish --access public
          fi
