# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Static Analysis
on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
        description: PHP version to use in major.minor format (e.g. 8.0)

permissions: {}

jobs:
  phpstan:
    name: PHPStan on PHP ${{ inputs.php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Run PHPStan
        uses: johnbillion/plugin-infrastructure/.github/actions/phpstan@composite-phpstan
        with:
          php: ${{ inputs.php }}

  semgrep:
    name: Semgrep
    if: ${{ inputs.php != '7.4' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    container:
      image: semgrep/semgrep:1.103.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Run semgrep
        run: semgrep --config "p/wordpress" --verbose .
