# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Static Analysis
on:
  workflow_call:
    inputs:
      min-php:
        required: true
        type: string
        description: Minimum supported version of PHP in major.minor format (e.g. 8.0)
      max-php:
        required: true
        type: string
        description: Maximum supported version of PHP in major.minor format (e.g. 8.0)

permissions: {}

jobs:
  phpstan-max-php:
    name: PHPStan on PHP ${{ inputs.max-php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Run PHPStan
        uses: johnbillion/plugin-infrastructure/actions/phpstan@composite-phpstan
        with:
          php: ${{ inputs.max-php }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  phpstan-min-php:
    name: PHPStan on PHP ${{ inputs.min-php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Run PHPStan
        uses: johnbillion/plugin-infrastructure/actions/phpstan@composite-phpstan
        with:
          php: ${{ inputs.min-php }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semgrep:
    name: Semgrep
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    container:
      image: semgrep/semgrep:1.103.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Run semgrep
        run: semgrep --config "p/wordpress" --verbose .
