# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  workflow_call:
    inputs:
      wp:
        required: true
        type: string
        description: WordPress version to use in major.minor format (e.g. 6.4), or "latest" or "nightly"
      php:
        required: true
        type: string
        description: PHP version to use in major.minor format (e.g. 8.0)
      node:
        required: true
        type: boolean
        description: Whether to run the Node build step
      cache:
        required: false
        type: boolean
        description: Whether to cache package dependencies
        default: true

permissions: {}

jobs:
  acceptance:
    name: PHP ${{ inputs.php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      LOCAL_PHP: ${{ '8.4' == inputs.php && 'php@sha256:56d6cbf10d25bfcb80852c09c2fc2e967922881b233b6161ad2999df509eb59a' || '8.3' == inputs.php && 'php@sha256:c0ba85936a9d1ac2c98bf3da2d62ceb0e5787a6b11e383630df0c5a5bf2534b5' || format( 'php:{0}-fpm', inputs.php ) }}
      LOCAL_CLI: ${{ '8.4' == inputs.php && 'cli@sha256:379f27b0c623c5cee5a7fbef1d617ce47fd3ba19158bac2e51861876fd68fdbf' || '8.3' == inputs.php && 'cli@sha256:85ad7d7a9c3bd9a8775fc83aea7f7dfc0aad25b2bc4f7d740696b28cd2a0ef89' || format( 'cli:{0}-fpm', inputs.php ) }}
      LOCAL_WP_DEBUG: ${{ inputs.php < 8.1 && 1 || 0 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Configure environment variables
      run: | #shell
        echo PHP_FPM_UID="$(id -u)" >> "$GITHUB_ENV"
        echo PHP_FPM_GID="$(id -g)" >> "$GITHUB_ENV"

    - name: Install PHP
      uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # 2.35.5
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      if: ${{ inputs.cache }}
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      if: ${{ inputs.cache }}
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-8.0-${{ hashFiles('composer.json') }}

    - name: Install Composer dependencies
      run: | #shell
        if [ "${WP_VERSION}" == "latest" ]; then
          composer install --dev
        elif [ "${WP_VERSION}" == "nightly" ]; then
          composer require --dev --update-with-dependencies roots/wordpress-full="dev-main"
        elif [[ "${WP_VERSION}" =~ ^[0-9]\.[0-9]$ ]]; then
          composer require --dev --update-with-dependencies roots/wordpress-full="~${WP_VERSION}.0"
        else
          composer require --dev --update-with-dependencies roots/wordpress-full="${WP_VERSION}"
        fi
      env:
        WP_VERSION: ${{ inputs.wp }}

    - name: Setup node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: '.nvmrc'
        cache: ${{ inputs.cache && 'npm' || '' }}

    - name: Install node dependencies
      run: npm ci --no-audit --no-fund

    - name: Run the build
      if: ${{ inputs.node }}
      run: npm run build

    - name: Start Docker environment
      run: composer exec tests-start

    - name: Debugging
      run: | #shell
        echo "=== Docker ==="
        docker --version
        docker compose version
        docker compose ps
        echo "=== PHP ==="
        docker compose exec php php --version
        docker compose exec php php -m
        echo "=== Database ==="
        docker compose exec database mariadb --version
        echo "=== WP-CLI ==="
        docker compose exec --user wp_php wpcli wp core version

    - name: Run the tests
      run: composer run test:acceptance

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: acceptance-wp-${{ inputs.wp }}-php-${{ inputs.php }}
        path: tests/_output
        if-no-files-found: error
