# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build
on:
  workflow_call:
    inputs:
      node:
        required: false
        type: boolean
        default: true
        description: Whether to run the Node build step and add the assets to the commit
      vendor:
        required: false
        type: boolean
        default: true
        description: Whether to generate the Composer autoloader files and add them to the commit

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP
      if: ${{ inputs.vendor }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Generate autoload file
      if: ${{ inputs.vendor }}
      run: |
        composer install
        composer run build-vendor
        git add -f vendor/autoload.php
        git add -f vendor/composer/*

    - name: Build Assets
      if: ${{ inputs.node }}
      run: |
        npm run build
        git add -f assets/*

    - name: Setup version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Tag
      run: |
        echo "Releasing version $VERSION ..."
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b "release-$VERSION"
        git commit -m "Release $VERSION"
        git tag "$VERSION"
        git push --tags
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
