# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string

jobs:
  test:
    name: PHP / PHP ${{ inputs.php }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure environment variables
      run: |
        echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
        echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Composer cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ inputs.php }}-composer-${{ hashFiles('composer.json') }}

    - name: PHPCS and PHPStan cache
      uses: actions/cache@v3
      with:
        path: tests/cache
        key: ${{ inputs.php }}-phpcs-${{ hashFiles('composer.json') }}

    - name: Debugging
      run: |
        php --version
        composer --version

    - name: Composer validate
      run: composer validate --strict --no-check-lock

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run static analysis
      run: composer test:phpstan

    - name: Run code sniffer
      run: composer test:phpcs
