# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  workflow_call:
    inputs:
      wp:
        required: true
        type: string
        description: WordPress version to use in major.minor format (e.g. 6.4), or "latest" or "nightly"
      php:
        required: true
        type: string
        description: PHP version to use in major.minor format (e.g. 8.0)
      cache:
        required: false
        type: boolean
        description: Whether to cache package dependencies
        default: true

permissions: {}

jobs:
  integration:
    name: PHP ${{ inputs.php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      LOCAL_PHP: ${{ inputs.php }}
      LOCAL_WP_DEBUG: ${{ inputs.php < 8.1 && 1 || 0 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Configure environment variables
      run: | #shell
        echo PHP_FPM_UID="$(id -u)" >> "$GITHUB_ENV"
        echo PHP_FPM_GID="$(id -g)" >> "$GITHUB_ENV"

    - name: Install PHP
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        extensions: xmlwriter
        coverage: none
        ini-file: development
      env:
        fail-fast: true

    - name: Get Composer cache directory
      if: ${{ inputs.cache }}
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      if: ${{ inputs.cache }}
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-${{ inputs.php }}-${{ hashFiles('composer.json') }}

    - name: Install Composer dependencies
      run: | #shell
        if [ "${WP_VERSION}" == "latest" ]; then
          composer install --dev
        elif [ "${WP_VERSION}" == "nightly" ]; then
          composer require --dev --update-with-dependencies roots/wordpress-full="dev-main"
        elif [[ "${WP_VERSION}" =~ ^[0-9]\.[0-9]$ ]]; then
          composer require --dev --update-with-dependencies roots/wordpress-full="~${WP_VERSION}.0" wp-phpunit/wp-phpunit="~${WP_VERSION}.0"
        else
          composer require --dev --update-with-dependencies roots/wordpress-full="${WP_VERSION}"
        fi
      env:
        WP_VERSION: ${{ inputs.wp }}

    - name: Start Docker environment
      run: composer exec tests-start

    - name: Debugging
      run: | #shell
        echo "=== Docker ==="
        docker --version
        docker compose version
        docker compose ps
        echo "=== PHP ==="
        docker compose exec php php --version
        docker compose exec php php -m
        echo "=== Database ==="
        docker compose exec database mariadb --version
        echo "=== WP-CLI ==="
        docker compose exec --user wp_php wpcli wp core version

    - name: Run integration tests
      run: composer run test:integration
