# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
        description: PHP version to use in major.minor format (e.g. 8.0)

permissions: {}

jobs:
  phpcs:
    name: ${{ inputs.php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Install PHP
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2, cs2pr
        coverage: none
        ini-file: development
      env:
        fail-fast: true

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-${{ inputs.php }}-${{ hashFiles('composer.json') }}

    - name: PHPCS cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: tests/cache/phpcs.json
        key: phpcs-${{ inputs.php }}-${{ hashFiles('composer.json') }}-${{ hashFiles('phpcs.xml.dist') }}

    - name: Debugging
      run: | #shell
        php --version
        composer --version

    - name: Composer validate
      run: composer validate --strict --no-check-lock

    - name: Install dependencies
      run: composer install

    - name: Create PHPCS cache directory
      run: mkdir --parents tests/cache

    - name: Run code sniffer
      run: composer run test:phpcs -- --report-checkstyle=./tests/cache/phpcs-report.xml
      id: phpcs

    - name: Show PHPCS results in PR
      if: ${{ always() && steps.phpcs.outcome == 'failure' }}
      run: cs2pr ./tests/cache/phpcs-report.xml || true
