# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  workflow_call:
    inputs:
      wp:
        required: true
        type: string
      php:
        required: true
        type: string
      node:
        required: false
        type: boolean
        default: true

jobs:
  test:
    name: WP ${{ inputs.wp }} / PHP ${{ inputs.php }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      LOCAL_PHP: ${{ inputs.php }}
      LOCAL_WP_DEBUG: ${{ inputs.php < 8.1 && 1 || 0 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure environment variables
      run: |
        echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
        echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Composer cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: 8.0-composer-${{ hashFiles('composer.json') }}

    - name: Install Composer dependencies
      run: |
        if [ "${{ inputs.wp }}" == "latest" ]; then
          composer install --dev --prefer-dist
        elif [ "${{ inputs.wp }}" == "nightly" ]; then
          composer require --dev --update-with-dependencies --prefer-dist roots/wordpress-full="dev-main"
        else
          composer require --dev --update-with-dependencies --prefer-dist roots/wordpress-full="~${{ inputs.wp }}.0"
        fi

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install node dependencies
      run: npm ci

    - name: Run the build
      if: ${{ inputs.node }}
      run: npm run build

    - name: Start Docker environment
      run: composer run test:start -- --quiet-pull

    - name: Log WordPress version
      run: docker compose run --rm wpcli core version

    - name: Run the tests
      run: composer run test:acceptance

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: acceptance-wp-${{ inputs.wp }}-php-${{ inputs.php }}
        path: tests/_output
