# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  workflow_call:
    inputs:
      wp:
        required: true
        type: string
      php:
        required: true
        type: string
      node:
        required: false
        type: boolean
        default: true

jobs:
  test:
    name: WP ${{ inputs.wp }} / PHP ${{ inputs.php }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      LOCAL_PHP: ${{ inputs.php }}
      LOCAL_WP_DEBUG: ${{ inputs.php < 8.1 && 1 || 0 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        extensions: xmlwriter
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Composer cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ inputs.php }}-composer-${{ hashFiles('composer.json') }}

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version
        docker --version
        docker-compose --version

    - name: Install Composer dependencies
      run: |
        composer require --dev --update-with-dependencies --prefer-dist roots/wordpress="${{ inputs.wp }}"

    - name: Setup node
      if: ${{ inputs.node }}
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install node dependencies
      if: ${{ inputs.node }}
      run: npm ci

    - name: Run the build
      if: ${{ inputs.node }}
      run: npm run build

    - name: Start Docker environment
      run: composer test:start

    - name: Log running Docker containers
      run: docker ps -a

    - name: Run unit tests
      run: composer test:integration
