# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Lint
on:
  workflow_call:

permissions: {}

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Only needed for private repos. Needed to clone the repo.
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      # actionlint is static checker for GitHub Actions workflow files.
      # See https://github.com/rhysd/actionlint.
      - name: Run actionlint
        uses: docker://rhysd/actionlint@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9 # v1.7.7
        with:
          args: "-color -verbose"

  octoscan:
    name: Octoscan
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # Required for codeql-action/upload-sarif to upload SARIF files.
      contents: read         # Only needed for private repos. Needed to clone the repo.
      actions: read          # Only needed for private repos. Needed for codeql-action/upload-sarif to read workflow run info.
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Run octoscan
        id: octoscan
        uses: synacktiv/action-octoscan@6b1cf2343893dfb9e5f75652388bd2dc83f456b0 # v1.0.0
        with:
          filter_triggers: ''

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@1b168cd39490f61582a9beae412bb7057a6b2c4e # v4.31.8
        with:
          sarif_file: "${{steps.octoscan.outputs.sarif_output}}"
          category: octoscan
          wait-for-processing: false

  zizmor:
    name: Zizmor
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # Required for codeql-action/upload-sarif to upload SARIF files.
      contents: read         # Only needed for private repos. Needed to clone the repo.
      actions: read          # Only needed for private repos. Needed for codeql-action/upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: false

      - name: Run zizmor
        run: uvx zizmor@1.18.0 --persona=auditor --format=sarif --strict-collection . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@1b168cd39490f61582a9beae412bb7057a6b2c4e # v4.31.8
        with:
          sarif_file: results.sarif
          category: zizmor
          wait-for-processing: false

  poutine:
    name: Poutine
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # Required for codeql-action/upload-sarif to upload SARIF files.
      contents: read         # Only needed for private repos. Needed to clone the repo.
      actions: read          # Only needed for private repos. Needed for codeql-action/upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Run Poutine
        uses: boostsecurityio/poutine-action@84c0a0d32e8d57ae12651222be1eb15351429228 # v0.15.2

      - name: Upload poutine SARIF file
        uses: github/codeql-action/upload-sarif@1b168cd39490f61582a9beae412bb7057a6b2c4e # v4.31.8
        with:
          sarif_file: results.sarif
          category: poutine
          wait-for-processing: false

  codeql:
    name: CodeQL
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # Required for codeql-action/analyze to report to code scanning.
      contents: read         # Only needed for private repos. Needed to clone the repo.
      actions: read          # Only needed for private repos. Needed for codeql-action/analyze to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@1b168cd39490f61582a9beae412bb7057a6b2c4e # v4.31.8
        with:
          languages: actions

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@1b168cd39490f61582a9beae412bb7057a6b2c4e # v4.31.8
        with:
          category: codeql
          wait-for-processing: false
