# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Assets
on:
  workflow_call:
    inputs:
      plugin:
        required: true
        type: string
        description: The plugin slug
      readme:
        required: true
        type: string
        description: The plugin readme file name, either readme.md or readme.txt
      node:
        required: false
        type: boolean
        default: true
        description: Whether to run the Node build step and add the assets to the commit
      vendor:
        required: false
        type: boolean
        default: true
        description: Whether to generate the Composer autoloader files and add them to the commit
      assets_dir:
        required: false
        type: string
        default: .wordpress-org
        description: The directory containing the assets to be deployed to WordPress.org
    secrets:
      WPORG_SVN_USERNAME:
        required: true
      WPORG_SVN_PASSWORD:
        required: true

jobs:
  wordpress:
    name: WordPress.org
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PHP
        if: ${{ inputs.vendor }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none
          ini-file: development
        env:
          fail-fast: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Composer Dependencies
        run: composer install

      - name: Generate autoload file
        if: ${{ inputs.vendor }}
        run: |
          composer run build-vendor
          git add -f vendor/autoload.php
          git add -f vendor/composer/*

      - name: Build Assets
        if: ${{ inputs.node }}
        run: |
          npm run build
          git add -f assets/*

      - name: Populate Changelog
        run: |
          node vendor/johnbillion/plugin-infrastructure/bin/changelog.js ${{ inputs.readme }}
          git add ${{ inputs.readme }}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Assets"

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-asset-update@2.1.2
        env:
          SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
          ASSETS_DIR: ${{ inputs.assets_dir }}
