# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Assets
on:
  workflow_call:
    inputs:
      plugin:
        required: true
        type: string
        description: The plugin slug
      readme:
        required: true
        type: string
        description: The plugin readme file name, either readme.md or readme.txt
      username:
        required: true
        type: string
        description: The WordPress.org SVN username
    secrets:
      WPORG_SVN_PASSWORD:
        required: true

permissions: {}

jobs:
  wordpress:
    name: WordPress.org
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    environment:
      name: WordPress.org
      url: "https://wordpress.org/plugins/${{ inputs.plugin }}/"
    steps:
      - name: Populate Changelog
        uses: johnbillion/action-changelog@trunk
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Update Readme
        run: | #shell
          echo "${CHANGELOG}" >> "${README}"
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          README: ${{ inputs.readme }}

      - name: Commit
        run: | #shell
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Assets"

      - name: Install SVN
        run: | #shell
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt-get install -y --no-install-recommends subversion
          svn --version

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7 # 2.2.0
        env:
          README_NAME: ${{ inputs.readme }}
          IGNORE_OTHER_FILES: true
          SVN_USERNAME: ${{ inputs.username }}
          SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
