# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test Plugins
on:
  pull_request:

permissions: {}

jobs:
  get-plugins:
    name: Get plugins
    permissions: {}
    if: github.event.pull_request.head.repo.full_name == 'johnbillion/plugin-infrastructure'
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.plugins.outputs.matrix }}
      source-pr-data: ${{ steps.source-pr-data.outputs.result }}
    steps:
      - name: Get the list of plugins to test
        id: plugins
        run: | #shell
          echo matrix='{"plugin":["user-switching","wp-crontrol"]}' >> "$GITHUB_OUTPUT"

      - name: Fetch the source PR data
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: source-pr-data
        with:
          retries: 2
          script: | #js
            const pr = await github.rest.pulls.get({
              owner: 'johnbillion',
              repo: 'plugin-infrastructure',
              pull_number: process.env.SOURCE_PR_NUMBER,
            });
            return {
              head_branch: pr.data.head.ref,
              head_sha: pr.data.head.sha,
              pr_number: pr.data.number,
              pr_link: pr.data.html_url,
            };
          github-token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
        env:
          SOURCE_PR_NUMBER: ${{ github.event.pull_request.number }}

  build-branch:
    name: Build test branch
    permissions:
      contents: write
    needs:
      - get-plugins
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout source branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ fromJson( needs.get-plugins.outputs.source-pr-data ).head_branch }}
          persist-credentials: true

      - name: Setup node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: | #shell
          npm install

      - name: Build package
        run: | #shell
          npm run build

      - name: Create and push built branch
        run: | #shell
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "${BRANCH_NAME}-built"
          git add -f dist/
          git commit -m "Built assets for testing"
          git push origin "${BRANCH_NAME}-built" --force
        env:
          BRANCH_NAME: ${{ fromJson( needs.get-plugins.outputs.source-pr-data ).head_branch }}

  open-pr:
    name: Open PR / ${{ matrix.plugin }}
    permissions: {}
    needs:
      - get-plugins
      - build-branch
    strategy:
      matrix: ${{ fromJSON( needs.get-plugins.outputs.matrix ) }}
      fail-fast: false
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    env:
      SHA_REF: ${{ fromJson( needs.get-plugins.outputs.source-pr-data ).head_sha }}
      BRANCH_REF: ${{ fromJson( needs.get-plugins.outputs.source-pr-data ).head_branch }}
      PR_LINK: ${{ fromJson( needs.get-plugins.outputs.source-pr-data ).pr_link }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: johnbillion/${{ matrix.plugin }}
          token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
          persist-credentials: false

      - name: Update workflow files
        run: | #shell
          find .github/workflows -name '*.yml' -type f -exec sed -i "s|johnbillion/plugin-infrastructure/\.github/workflows/\([^@]*\)@.*$|johnbillion/plugin-infrastructure/.github/workflows/\1@${SHA_REF}|g" {} \;

      - name: Update Composer dependencies
        if: hashFiles('composer.json') != ''
        run: | #shell
          sed -i "s|\"johnbillion/plugin-infrastructure\": \"[^\"]*\"|\"johnbillion/plugin-infrastructure\": \"dev-${BRANCH_REF}-built\"|g" composer.json

      - name: Setup node
        if: hashFiles('.nvmrc') != ''
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Update Node dependencies
        if: hashFiles('package.json') != ''
        run: | #shell
          npm install "@johnbillion/plugin-infrastructure@github:johnbillion/plugin-infrastructure#${BRANCH_REF}-built" --save-exact --save-dev --package-lock-only

      - name: Check the changed files
        run: | #shell
          git diff --color
          git status

      - name: Open PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v6
        id: cpr
        with:
          token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
          commit-message: Update Plugin Infrastructure to ${{ env.SHA_REF }}
          title: Test with plugin-infrastructure@${{ env.BRANCH_REF }}
          body: | #markdown
            This PR updates [Plugin Infrastructure](https://github.com/johnbillion/plugin-infrastructure) to `${{ env.BRANCH_REF }}` for testing purposes. This PR should not be merged.

            See ${{ env.PR_LINK }} for more details.

            This is an automated PR created by [the Test Plugins workflow](https://github.com/johnbillion/plugin-infrastructure/actions/workflows/test-plugins.yml).
          branch: test-plugin-infrastructure/${{ env.BRANCH_REF }}
          draft: true

      - name: Add PR link to the summary
        run: | #shell
          echo "${URL}" >> "$GITHUB_STEP_SUMMARY"
        env:
          URL: ${{ steps.cpr.outputs.pull-request-url }}

      - name: Write plugin PR data to JSON file
        run: | #shell
          echo "${PR_DATA}" > plugin-pr-data.json
        env:
          PR_DATA: ${{ toJson(steps.cpr.outputs) }}

      - name: Save plugin PR data as an artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: plugin-pr-data-${{ matrix.plugin }}
          path: plugin-pr-data.json
          if-no-files-found: error

  label:
    name: Label PR / ${{ matrix.plugin }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    needs:
      - get-plugins
      - open-pr
    timeout-minutes: 5
    strategy:
      matrix: ${{ fromJSON( needs.get-plugins.outputs.matrix ) }}
      fail-fast: false
    steps:
      - name: Download plugin PR data artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: plugin-pr-data-${{ matrix.plugin }}

      - name: Read the plugin PR data
        id: plugin-pr-data
        run: | #shell
          echo "pr_data=$(jq -c . plugin-pr-data.json)" >> "$GITHUB_OUTPUT"

      - name: Set labels
        run: | #shell
          gh --repo johnbillion/plugin-infrastructure label create "pr:${PLUGIN}:${PLUGIN_PR_NUMBER}" --force --color F4F4F4
          gh --repo johnbillion/plugin-infrastructure pr edit "${SOURCE_PR_NUMBER}" --add-label "pr:${PLUGIN}:${PLUGIN_PR_NUMBER}"
        env:
          GH_TOKEN: ${{ github.token }}
          SOURCE_PR_NUMBER: ${{ fromJson( needs.get-plugins.outputs.source-pr-data ).pr_number }}
          PLUGIN: ${{ matrix.plugin }}
          PLUGIN_PR_NUMBER: ${{ fromJson( steps.plugin-pr-data.outputs.pr_data ).pull-request-number }}

  check-status:
    name: Check PR / ${{ matrix.plugin }}
    permissions: {}
    needs:
      - get-plugins
      - open-pr
      - label
    strategy:
      matrix: ${{ fromJSON( needs.get-plugins.outputs.matrix ) }}
      fail-fast: false
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Download plugin PR data artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: plugin-pr-data-${{ matrix.plugin }}

      - name: Read the plugin PR data
        id: plugin-pr-data
        run: | #shell
          echo "pr_data=$(jq -c . plugin-pr-data.json)" >> "$GITHUB_OUTPUT"

      - name: Check the status of workflows
        run: | #shell
          echo "ℹ️ See the checks at https://github.com/johnbillion/${PLUGIN}/pull/${PLUGIN_PR_NUMBER}/checks"

          while true; do
            gh api "repos/johnbillion/${PLUGIN}/actions/runs?head_sha=${PLUGIN_HEAD_SHA}" --jq '[.workflow_runs[]]' > workflow_runs.json

            failed="$(jq 'map(select(.conclusion == "failure")) | length' workflow_runs.json)"
            cancelled="$(jq 'map(select(.conclusion == "cancelled")) | length' workflow_runs.json)"
            in_progress="$(jq 'map(select(.status != "completed")) | length' workflow_runs.json)"
            total="$(jq 'length' workflow_runs.json)"

            if [ "$failed" -gt 0 ]; then
              echo "❌ Some workflows failed."
              exit 1
            elif [ "$cancelled" -gt 0 ]; then
              echo "❌ Some workflows were cancelled."
              exit 1
            elif [ "$in_progress" -gt 0 ]; then
              echo "ℹ️ ${in_progress}/${total} workflows are still in progress. Waiting..."
              sleep 10
            else
              echo "✅ ${total}/${total} workflows passed."
              break
            fi
          done
        env:
          GH_TOKEN: ${{ github.token }}
          PLUGIN_PR_NUMBER: ${{ fromJson( steps.plugin-pr-data.outputs.pr_data ).pull-request-number }}
          PLUGIN_HEAD_SHA: ${{ fromJson( steps.plugin-pr-data.outputs.pr_data ).pull-request-head-sha }}
          PLUGIN: ${{ matrix.plugin }}
