# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Update Plugins
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: The tag name to update to
        required: true

permissions: {}

jobs:
  tag-data:
    name: Fetch tag data
    permissions: {}
    runs-on: ubuntu-24.04
    outputs:
      source-tag-data: ${{ steps.source-tag-data.outputs.result }}
    steps:
      - name: Fetch the source tag data
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: source-tag-data
        with:
          retries: 2
          script: | #js
            const tagName = process.env.TAG_NAME;

            // Get the tag reference
            const tagRef = await github.rest.git.getRef({
              owner: 'johnbillion',
              repo: 'plugin-infrastructure',
              ref: `tags/${tagName}`,
            });

            const tagSha = tagRef.data.object.sha;

            return {
              tag_name: tagName,
              tag_sha: tagSha,
              tag_url: `https://github.com/johnbillion/plugin-infrastructure/releases/tag/${tagName}`,
            };
        env:
          TAG_NAME: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.TAG_NAME }}

  update-plugin:
    name: Update ${{ matrix.plugin }}
    permissions: {}
    needs:
      - tag-data
    strategy:
      matrix:
        plugin:
          # - query-monitor
          - user-switching
          - wp-crontrol
      fail-fast: false
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    env:
      TAG_NAME: ${{ fromJson( needs.tag-data.outputs.source-tag-data ).tag_name }}
      TAG_SHA: ${{ fromJson( needs.tag-data.outputs.source-tag-data ).tag_sha }}
      TAG_URL: ${{ fromJson( needs.tag-data.outputs.source-tag-data ).tag_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: johnbillion/${{ matrix.plugin }}
          token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
          persist-credentials: false

      - name: Update workflow files
        run: | #shell
          find .github/workflows -name '*.yml' -type f -exec sed -i "s|johnbillion/plugin-infrastructure/\.github/workflows/\([^@]*\)@.*$|johnbillion/plugin-infrastructure/.github/workflows/\1@${TAG_SHA} # ${TAG_NAME}|g" {} \;

      - name: Update Composer dependencies
        if: hashFiles('composer.json') != ''
        run: | #shell
          sed -i "s|\"johnbillion/plugin-infrastructure\": \"[^\"]*\"|\"johnbillion/plugin-infrastructure\": \"${TAG_NAME}\"|g" composer.json

      - name: Setup node
        if: hashFiles('.nvmrc') != ''
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Update Node dependencies
        if: hashFiles('package.json') != ''
        run: | #shell
          npm install "@johnbillion/plugin-infrastructure@${TAG_NAME}" --save-exact --save-dev --package-lock-only

      - name: Check the changed files
        run: | #shell
          git diff --color
          git status

      - name: Open PR
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v6
        id: cpr
        with:
          token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
          commit-message: Update plugin-nfrastructure to ${{ env.TAG_NAME }}
          title: Update Plugin Infrastructure to ${{ env.TAG_NAME }}
          body: | #markdown
            This PR updates [Plugin Infrastructure](https://github.com/johnbillion/plugin-infrastructure) to version `${{ env.TAG_NAME }}`.

            See ${{ env.TAG_URL }} for release details.

            This is an automated PR created by [the Update Plugins workflow](https://github.com/johnbillion/plugin-infrastructure/actions/workflows/update-plugins.yml).
          branch: update-plugin-infrastructure/${{ env.TAG_NAME }}
          draft: false
