# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Workflows
on:
  pull_request: null
  push:
    branches:
    - trunk
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run actionlint
      uses: docker://rhysd/actionlint:latest
      with:
        args: "-color -verbose -shellcheck="
